name: example
description: A project that showcases how to enable the recommended lints for Flutter apps, packages, and plugins within Apadmi.

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  apadmi_lints:
    path: ../
