name: example
description: A project that showcases how to enable the recommended lints for Flutter apps, packages, and plugins within Pinch.

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pinch_lints:
    path: ../
